# Generated by Django 5.0.3 on 2024-04-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
