# Generated by Django 5.0.3 on 2024-04-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Progress',
            new_name='progress',
        ),
        migrations.AddField(
            model_name='education',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
