# Generated by Django 5.0.3 on 2024-04-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_rename_progress_skill_progress_education_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.DateField(),
        ),
    ]
